apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
spec:
  capacity:
    storage: 15Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /nfs
    server: 104.196.5.58
  persistentVolumeReclaimPolicy: Recycle
